# Generated by Django 5.2.5 on 2025-08-10 11:46

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings

class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_preload_exercises"),
    ]

    operations = [
        # Create the normalized session table
        migrations.CreateModel(
            name="WorkoutSession",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(default="Workout", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="workout_sessions", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        # Add a NEW FK on WorkoutLog that does NOT clash with your existing session_id string
        migrations.AddField(
            model_name="workoutlog",
            name="session_ref",
            field=models.ForeignKey(
                to="tracker.workoutsession",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entries",
                null=True,
                blank=True,
                db_index=True,
            ),
        ),
    ]

