# Generated by Django 5.2.5 on 2025-08-10 15:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_alter_workoutlog_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workoutlog',
            options={},
        ),
        migrations.RenameField(
            model_name='workoutsession',
            old_name='date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='workoutlog',
            name='client_session_id',
        ),
        migrations.RemoveField(
            model_name='workoutsession',
            name='name',
        ),
        migrations.RemoveField(
            model_name='workoutsession',
            name='user',
        ),
        migrations.AddField(
            model_name='workoutlog',
            name='session_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='session_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.workoutsession'),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
