# Generated by Django 5.2.5 on 2025-08-11 11:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_alter_workoutlog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutlog',
            name='name',
            field=models.CharField(default='Workout', max_length=100),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='session_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
