# Generated by Django 5.2.5 on 2025-08-11 13:57

import django.db.models.deletion
import tracker.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_workoutlog_name_alter_workoutlog_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutlog',
            name='exercise_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.exercise'),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='name',
            field=models.CharField(blank=True, default='Workout', max_length=100),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='session_id',
            field=models.CharField(db_index=True, default=tracker.models.generate_uuid, max_length=36),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
